### ISSUE TITLE
Module doesn't start correctly

### ISSUE THREAD

**Issue by Maciek416** [npm/npme-auth-oauth2-restricted#4]
When I run this on our `npmE` instance and tail `npme-auth`, I see this:

```
{"time":"2018-03-21T22:01:47.526Z","hostname":"xxxxxxxxx","pid":5,"level":"info","name":"npme","message":"npm-auth-ws listening at http://0.0.0.0:5000"}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to xxxxxxxxx:6379 failed - connect ECONNREFUSED xxxxxxxxx:6379
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1078:14)
```

With the above error appearing in the logs for the auth container, when the plugin is active, going to `/login` shows a password screen, which takes any username/password. After this, it proceeds to a google oauth screen as hoped, **but,** it's possible to use any google oauth2 id to sign in, and `user-whitelist.txt` doesn't appear to have an effect.

**edit**: A colleague of mine is wondering if this is perhaps due to the redis container starting a little late.

**Comment by bcoe** [comment]
@Maciek416 if the redis container starts late, it should be smart about killing the process and coming back up again (with Redis now available).

Perhaps we need to `process.exit` when this error is encountered?
